COPA.Reports/Models/COPAPaymentBreakdown.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace COPA.Reports.ViewModels
{
    public class COPAPaymentBreakdown
    {
        public int PaymentID { get; set; }
        public DateTime PaymentDate { get; set; }
        public string Client { get; set; }
        public decimal AmountPaid { get; set; }
        public string PaymentStatus { get; set; }
        public decimal Fee { get; set; }
        public string FailureReason { get; set; }
        public int ConfirmationNumber { get; set; }
        public string ClientSystemBillID { get; set; }
        public string AutomationImagePath { get; set; }
        public string ManualImagePath { get; set; }
        public decimal AmountToBePaid { get; set; }
        public string ProviderName { get; set; }
        public string AccountNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string TemplateName { get; set; }
    }
}

COPA.Reports/Controllers/BreakdownController.cs
using COPA.Reports.BLL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace COPA.Reports.Controllers
{
    public class BreakdownController : Controller
    {
        private readonly IPaymentBreakdownLogic paymentBreakdownLogic;

        public BreakdownController(IPaymentBreakdownLogic paymentBreakdownLogic)
        {
            this.paymentBreakdownLogic = paymentBreakdownLogic;
        }

        [HttpGet]
        public IActionResult Index() =>
            View(paymentBreakdownLogic);

        [HttpGet]
        public IActionResult GetNewBreakdownTimespan(int start, int end) =>
            PartialView("_BreakdownTable", paymentBreakdownLogic);
    }
}

COPA.Reports/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace COPA.Reports.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

COPA.Reports/Views/Breakdown/Index.cshtml
@model COPA.Reports.BLL.PaymentBreakdownLogic
@{
    ViewData["Title"] = "COPA Health Breakdown";
}

<div class="container-fluid">
    <h2>
        COPA Health Breakdown
    </h2>
    <div>
        <table id="breakdownTable" class="table table-striped table-bordered table-sm table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Payment ID</th>
                    <th>Control Number</th>
                    <th>Invoice Number</th>
                    <th>Payment Date</th>
                    <th>Client</th>
                    <th>Provider</th>
                    <th>Amount Paid</th>
                    <th>Fee</th>
                    <th>Amount To Be Paid</th>
                    <th>Account Number</th>
                    <th>Payment Status</th>
                    <th>Failure Reason</th>
                    <th>Confirmation Number</th>
                    <th>Automation Image Path</th>
                    <th>Manual Image Path</th>
                </tr>
            </thead>
            @{
                await Html.RenderPartialAsync("_BreakdownTable", Model);
             }
        </table>
    </div>
</div>

COPA.Reports/Views/Breakdown/_BreakdownTable.cshtml
@model COPA.Reports.BLL.PaymentBreakdownLogic

<tbody>
    @{
        foreach(var payment in Model.GetCOPAPaymentBreakdowns())
            {
                <tr>
                    <td>@payment.PaymentID</td>
                    <td>@payment.ClientSystemBillID</td>
                    <td>@payment.InvoiceNumber</td>
                    <td>@payment.PaymentDate</td>
                    <td>@payment.Client</td>
                    <td>@payment.ProviderName</td>
                    <td>@payment.AmountPaid</td>
                    <td>@payment.Fee</td>
                    <td>@payment.AmountToBePaid</td>
                    <td>@payment.AccountNumber</td>
                    <td>@payment.PaymentStatus</td>
                    <td>@payment.FailureReason</td>
                    <td>@payment.AccountNumber</td>
                    <td>@payment.AutomationImagePath</td>
                    <td>@payment.ManualImagePath</td>
                </tr>
            }
    }
</tbody>

COPA.Reports/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

COPA.Reports/Views/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

COPA.Reports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - COPA.Reports</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COPA.Reports</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Breakdown" asp-action="Index">COPA Health Breakdown</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="breakdownStyle">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - COPA.Reports - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>